language: go

sudo: required

go_import_path: github.com/google/pprof

env: SKIP_GRAPHVIZ=0

matrix:
  include:
    - os: linux
      go: 1.7.x
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libelf-dev
            - libssl-dev
            - libcap-dev
            - linux-tools-`uname -r`
            - linux-cloud-tools-`uname -r`
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
    - os: linux
      go: 1.8.x
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libelf-dev
            - libssl-dev
            - libcap-dev
            - linux-tools-`uname -r`
            - linux-cloud-tools-`uname -r`
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
    - os: linux
      go: 1.9.x
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libelf-dev
            - libssl-dev
            - libcap-dev
            - linux-tools-`uname -r`
            - linux-cloud-tools-`uname -r`
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
    - os: linux
      go: master
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.8
            - libelf-dev
            - libssl-dev
            - libcap-dev
            - linux-tools-`uname -r`
            - linux-cloud-tools-`uname -r`
      env:
         - MATRIX_EVAL="CC=gcc-4.8 && CXX=g++-4.8"
    - os: osx
      osx_image: xcode6.4
      go: 1.8.x
      env: SKIP_GRAPHVIZ=1
    - os: osx
      osx_image: xcode6.4
      go: 1.9.x
      env: SKIP_GRAPHVIZ=1
    - os: osx
      osx_image: xcode6.4
      go: master
      env: SKIP_GRAPHVIZ=1
    - os: osx
      osx_image: xcode7.3
      go: 1.8.x
    - os: osx
      osx_image: xcode7.3
      go: 1.9.x
    - os: osx
      osx_image: xcode7.3
      go: master
    - os: osx
      osx_image: xcode8.3
      go: 1.8.x
    - os: osx
      osx_image: xcode8.3
      go: 1.9.x
    - os: osx
      osx_image: xcode8.3
      go: master

addons:
  apt:
    packages:
      - graphviz

before_install:
  - go get -u github.com/golang/lint/golint honnef.co/go/tools/cmd/... github.com/ianlancetaylor/demangle
  - if (("$TRAVIS_OS_NAME" == "osx") && (!"$SKIP_GRAPHVIZ")); then brew update          ; fi
  - if (("$TRAVIS_OS_NAME" == "osx") && (!"$SKIP_GRAPHVIZ")); then brew install graphviz; fi
  - if ("$TRAVIS_OS_NAME" == "osx"); then brew install gcc48 && CC=gcc-4.8 && CXX=g++-4.8; fi

compiler:
  - clang
  - gcc

script:
  - gofmtdiff=$(gofmt -s -d .) && if [ -n "$gofmtdiff" ]; then printf 'gofmt -s found:\n%s\n' "$gofmtdiff" && exit 1; fi
  - golintlint=$(golint ./...) && if [ -n "$golintlint" ]; then printf 'golint found:\n%s\n' "$golintlint" && exit 1; fi
  - go tool vet -all .
  - gosimple ./...
  - ./test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
